FROM ubuntu:24.04

RUN apt-get update

# Install build tools
RUN apt-get install -y git
RUN apt-get install -y gcc-14 && ln -s /usr/bin/gcc-14 /usr/bin/gcc
RUN apt-get install -y g++-14 && ln -s /usr/bin/g++-14 /usr/bin/g++
RUN apt-get install -y clang-18 && ln -s /usr/bin/clang++-18 /usr/bin/clang++ && ln -s /usr/bin/clang-18 /usr/bin/clang

# Install CMake
RUN apt-get install -y ca-certificates gpg wget
RUN test -f /usr/share/doc/kitware-archive-keyring/copyright || \
    wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
RUN echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ noble main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null
RUN apt-get update
RUN apt-get install -y kitware-archive-keyring
RUN apt-get install -y cmake

# Install Ninja
RUN apt-get install -y ninja-build

# Disable safe directory
RUN git config --global --add safe.directory '*'